acu83269 - update seed script to support package override on Ubuntu

diff --git a/cookbooks/rightimage/files/default/rightimage_repo b/cookbooks/rightimage/files/default/rightimage_repo
--- a/cookbooks/rightimage/files/default/rightimage_repo
+++ b/cookbooks/rightimage/files/default/rightimage_repo
@@ -22,165 +22,54 @@
 ## Setup environment used by the remainder of this script
 #############################################################################
 
+. /opt/rightscale/etc/init.d/rightscale_functions
+
 #Set Root Home and working directory for temp files
 export WORKING_DIR=/var/cache/rightscale/tarballs
 # TBD: find out where this is going to reside for real, once its determined
 # TBD: finish up support for repos
 export RIGHTLINK_DEV_REPO=http://rightlink-dev.s3.amazonaws.com
 
-function init_os_state() {
-  if [ -e /usr/bin/lsb_release ]; then
-    # For LSB-compliant distros, query lsb_release...
-    case `lsb_release -si` in
-      Ubuntu*|Debian*)
-        export RS_BASE_OS=debian
-        export PKG_MGR_INSTALL='apt-get install -y'
-        export PKG_MGR_REMOVE='apt-get purge -y'
-        export DEBIAN_FRONTEND=noninteractive
-        ;;
-      CentOS*|Fedora*|RedHat*|EnterpriseEnterprise*)
-        export RS_BASE_OS=redhat
-        export PKG_MGR_INSTALL='yum install -y'
-        export PKG_MGR_REMOVE='yum remove -y'
-        ;;
-      SUSE*)
-        export RS_BASE_OS=suse
-        export PKG_MGR_INSTALL='zypper install -y'
-        export PKG_MGR_REMOVE='zypper remove -y'
-        ;;
-      *)
-        export RS_BASE_OS=unknown
-        ;;
-    esac
-  elif [ -e /etc/fedora-release ]; then
-    #Fedora doesn't always have lsb_release, but it does have a release file
-    export RS_BASE_OS=redhat
-    export PKG_MGR_INSTALL='yum install -y'
-    export PKG_MGR_REMOVE='yum remove -y'
-  else
-    #Don't know our distro whatsoever...
-    export RS_BASE_OS=unknown
-  fi
-
-  # Get the architecture used by the packaging system on this machine
-  if [ "$RS_BASE_OS" == "debian" ]; then
-    #Debian's package manager tells us its architecture directly
-    export RS_ARCH=`dpkg --print-architecture || echo unknown`
-  else
-    #For RedHat and other distros, we need to guess using a heuristic based on the
-    #output of uname.
-    export RS_ARCH=`uname -i || echo unknown`
-
-    #On some systems, uname -i fails
-    if [ "$RS_ARCH" == "unknown" ]; then
-      export RS_ARCH=`uname -m || echo unknown`
-    fi
-
-    #Sometimes i686 is reported; this is equivalent to i386 for our purposes
-    if [ "$RS_ARCH" == "i686" ]; then
-      export RS_ARCH="i386"
-    fi
-  fi
-
-  # Source function library and networking configuration for Redhat-based distros
-  if [ "$RS_BASE_OS" == "redhat" ]; then
-    . /etc/rc.d/init.d/functions
-    [ -r /etc/sysconfig/network ] && . /etc/sysconfig/network
-  fi
-
-  ###############################################################################
-  ## Determine whether the script has everything it needs to continue
-  ###############################################################################
-
-  if [ "$RS_BASE_OS" == "unknown" -o "$RS_ARCH" == "unknown" ]; then
-    logger -st RightScale "Unsupported OS/architecture $RS_BASE_OS/$RS_ARCH; exiting."
-    exit 2
-  fi
-
-  # Check that networking is up. (Only works on Redhat-based systems.)
-  [ "${NETWORKING}" == "no" ] && exit 1
-}
-
 ###############################################################################
 ## Define some functions to be called by the start() function (see below)
 ###############################################################################
 
 
-function configure_proxy() {
-  if [ -f /etc/profile.d/http_proxy.sh ]; then
-    . /etc/profile.d/http_proxy.sh
-  fi
-}
-
-function wait_for_metadata() {
-  local cloud_file=/etc/rightscale.d/cloud
-  if [ -s $cloud_file ]; then 
-    local rs_cloud=`cat $cloud_file`
-    /opt/rightscale/bin/cloud --name $rs_cloud --action bootstrap > /dev/null
-    result=$?
-    if [ $result -ne 0 ]; then
-      logger -st RightScale "WARNING: Failed to get userdata for cloud $rs_cloud"
-    fi
-  else
-    logger -st RightScale "WARNING: Cloud was not defined in $cloud_file, can not get userdata"
-  fi
-}
-
-function populate_rs_variables() {
-  source /var/spool/cloud/user-data.sh
-}
-
 function download_tarball() {
   local working_dir=$1
   local url=$2
   local curl_opt=(-s -S -f -L --retry 7)
-  local net_wait_count=0
 
   local tarball_name=`basename $url`
   local file_on_disk=$working_dir/$tarball_name
   local code=500
   mkdir -p $working_dir
-  while [ "$code" -ge "500" ]; do
-    logger -st RightScale "Downloading $temp_tarball_name from $url"
-    code=`curl "${curl_opt[@]}" -w '%{http_code}' -o $file_on_disk $url`
-    logger -st RightScale "curl returned code: $code"
-    # 000 denotes network unreachable, wait up to 30 seconds for
-    # networking to be set up, but only once.  This works around
-    # a race condition for azure
-    if [ "$code" -eq "000" ] && [ $net_wait_count -lt 30 ]; then
-      logger -st RightScale "Networking not set yet, waiting up to 30 seconds for it to appear"
-    fi
-    while [ "$code" -eq "000" ] && [ $net_wait_count -lt 30 ]; do
-      sleep 1
-      net_wait_count=`expr $net_wait_count + 1`
-      code=`curl "${curl_opt[@]}" -w '%{http_code}' -o $file_on_disk $url`
-    done
-    final_tarball_name=$(basename $url)
-  done
-
-  if [ ! -e $file_on_disk ]; then
-    logger -st RightScale "ERROR: Failed to download tarball from from $1"
+  logger -st RightScale "Downloading $tarball_name to $working_dir from $url"
+  if url_exists $url; then
+    curl "${curl_opt[@]}" -o $file_on_disk $url
+  else
+    logger -st RightScale "ERROR: Tarball url $url doesn't exist"
     exit 1;
   fi
-}
 
-function remove_me() {
-  my_name=`readlink -e $0`
-
-  if [ "$RS_BASE_OS" == "debian" ]; then
-    update-rc.d -f `basename $my_name` remove
-  elif [ "$RS_BASE_OS" == "redhat" ]; then
-    chkconfig --del `basename $my_name`
+  if [ ! -e $file_on_disk ]; then
+    logger -st RightScale "ERROR: Failed to download tarball from from $url"
+    exit 1;
   fi
 }
 
 function enable_repos() {
   local url=$1
   if [ "$RS_BASE_OS" = "redhat" ]; then
+    if ! is_simple_repo $url; then
+      url="$url/1/el/\$releasever/\$basearch"
+    fi
+  fi
+  if [ "$RS_BASE_OS" = "redhat" ]; then
     cat >/etc/yum.repos.d/rightlink.repo<<-EOF
 [rightlink]
 name=RightScale RightLink
-baseurl=$1
+baseurl=$url
 enabled=1
 gpgcheck=0
 priority=1
@@ -191,8 +80,8 @@ EOF
       logger -st RightScale "ERROR: Need lsb_release installed to use package override mode!"
       exit 1
     fi
-    echo "deb $url $codename main" > /etc/sources.list.d/rightlink.list
-    apt-get update
+    echo "deb $url $codename main" > /etc/apt/sources.list.d/rightlink.list
+    apt-get update > /dev/null
   else
     logger -st RightScale "Package override tag currently not supported on SUSE"
     exit 1
@@ -203,34 +92,63 @@ function disable_repos() {
   if [ "$RS_BASE_OS" = "redhat" ]; then
     sed -i s/enabled=1/enabled=0/ /etc/yum.repos.d/rightlink.repo
   elif [ "$RS_BASE_OS" = "debian" ]; then
-    sed -i s/^deb/#deb/ /etc/sources.list.d/rightlink.list
-    apt-get update
+    sed -i s/^deb/#deb/ /etc/apt/sources.list.d/rightlink.list
+    apt-get update > /dev/null
   fi
+}
+
+function url_exists() {
+  local url=$1
+  local curl_opt=(--silent --show-error --fail --location --head --retry 7)
+  for attempt in 1 2 3; do
+    code=`curl "${curl_opt[@]}" -w '%{http_code}' -o /dev/null $url 2>/dev/null`
+    # 000 indicates network error, sometimes network takes a little time to settle on Azure
+    # 500 errors can be temporary, so retry after a little bit
+    if [[ $code -ge 500 ]] || [[ "$code" == "000" ]]; then
+      logger -st RightScale "url_exists for $url encountered code $code, retry attempt $attempt"
+      sleep 10
+    elif [[ $code -ge 200 ]] && [[ $code -le 299 ]]; then
+      return 0
+    else
+      return 1
+    fi
+  done
+  logger -st RightScale "url_exists is done retrying"
+  return 1
 }
 
 function install_packages() {
   local version=$1
 
+  if [ "$RS_BASE_OS" = "debian" ]; then
+    pkg_cmd='apt-get install -y'
+    version_sep="="
+  else
+    pkg_cmd='yum install -y'
+    version_sep="-"
+  fi
+
   if [ -z "$version" ]; then
-    logger -st RightScale "Installing packages rightlink, rightlink-sandbox with latest version in repo"
-    $PKG_MGR_INSTALL rightlink rightlink-sandbox
+    logger -st RightScale "Installing packages rightlink, rightlink-sandbox with latest version"
+    $pkg_cmd rightlink rightlink-sandbox
   else
     logger -st RightScale "Installing packages rightlink, rightlink-sandbox with version=$version"
-    if [ "$RS_BASE_OS" = "debian" ]; then
-      $PKG_MGR_INSTALL rightlink=$version rightlink-sandbox=$version
-    else
-      $PKG_MGR_INSTALL rightlink-$version rightlink-sandbox-$version
-    fi
+    $pkg_cmd rightlink${version_sep}${version} rightlink-sandbox${version_sep}${version}
   fi
   result=$?
   if [ $result -ne 0 ]; then
-    logger -st RightScale "Failed to install package.  Cannot continue."
+    logger -st RightScale "Failed to install package, result was $result. Cannot continue."
     exit 1
   fi
 }
 
 function install_tarball() {
-  $PKG_MGR_REMOVE rightlink || true
+  if [ "$RS_BASE_OS" = "debian" ]; then
+    pkg_cmd='apt-get purge -y'
+  else
+    pkg_cmd='yum remove -y'
+  fi
+  $pkg_cmd rightlink || true
   mkdir -p /opt
   tar -C /opt/ -zxf $1/$2
 
@@ -243,48 +161,74 @@ function install_tarball() {
   fi
 }
 
+function is_simple_repo() {
+  local repourl=$1
+  if [ "$RS_BASE_OS" == "debian" ]; then
+    return 1
+  elif [ "$RS_BASE_OS" == "redhat" ]; then
+    if url_exists "$repourl/repodata/repomd.xml"; then
+      return 0
+    else
+      return 1
+    fi
+  fi
+  return 1
+}
+
 function start() {
-  logger -st RightScale "Running RightLink Updater"
-
-  init_os_state
-  configure_proxy
-  wait_for_metadata
-  populate_rs_variables
-
   # If RS_SRC is not defined in userdata, we're booting in "production mode."
   # In this case, we will use the rightlink already on disk.
   # If RS_SRC is defined in userdata, we're booting in "development mode."
   # RS_SRC must be a url pointing to either a tarball or yum/apt repo, in
-  # which case we either:
-  #  If a tarball: Upgrade the package from an http URL pointing to a 
-  #    yum/debian repo
-  #  If a repo: Remove the rightimage-base package, and untar the tarball to 
-  #    /opt/rightscale
+  # which case:
+  #  If repo: Setup the repo pointed to by the URL and upgrade the package
+  #  If tarball: Remove the rightlink package (but not the sandbox), and
+  #    untar the tarball to /opt/rightscale. Run post_install_dev.sh script.
 
-  if [ -n "$RS_SRC" ]; then 
-    if [[ $RS_SRC =~ \.tar|\.tgz|\.tbz ]]; then 
-      logger -st RightScale "Fetching and installing RightLink development tarball from $RS_SRC"
-      tarball_name=`basename $RS_SRC`
-      download_tarball $WORKING_DIR $RS_SRC
-      install_tarball $WORKING_DIR $tarball_name
-    elif [[ $RS_SRC =~ http ]]; then 
-      logger -st RightScale "Installing RightLink development packages from repo $RS_SRC"
-      enable_repos $RS_SRC
-      install_packages
-      disable_repos
-    else
-      logger -st RightScale "Installing RightLink development packages with version $RS_SRC from dev repo $RIGHTLINK_DEV_REPO"
-      enable_repos $RIGHTLINK_DEV_REPO
-      install_packages $RS_SRC
-      disable_repos
-    fi
-    remove_me
-    service rightboot start
-    service rightscale start
-    service rightlink start
+  init_os_state
+  configure_proxy
+  init_cloud_state 1
+
+  export DEBIAN_FRONTEND=noninteractive
+
+  # Check that networking is up. (Only works on Redhat-based systems.)
+  [ "${NETWORKING}" == "no" ] && exit 1
+
+  if [ -e /var/lib/rightscale/right_link/booted ]; then
+    # If booted is already set, don't try to update a second time
+    logger -st RightScale "Starting RightLink"
+    exit 0
+  elif [ -z $RS_SRC ]; then
+    logger -st RightScale "Starting RightLink"
+    exit 0
   else
-    logger -st RightScale "No RS_SRC value found, proceeding with normal RightLink startup"
+    logger -st RightScale "Running RightLink updater"
   fi
+
+  if [[ $RS_SRC =~ \.tar|\.tgz|\.tbz ]]; then 
+    logger -st RightScale "Fetching and installing RightLink development tarball from $RS_SRC"
+    tarball_name=`basename $RS_SRC`
+    download_tarball $WORKING_DIR $RS_SRC
+    install_tarball $WORKING_DIR $tarball_name
+  elif [[ $RS_SRC =~ http ]]; then 
+    if [[ $RS_SRC =~ @ ]]; then
+      IFS='@' read -a url_parts <<< "$RS_SRC"
+      RS_SRC=${url_parts[0]}
+      VERSION=${url_parts[1]}
+    fi
+    logger -st RightScale "Installing RightLink development packages from repo $RS_SRC"
+    enable_repos $RS_SRC
+    install_packages $VERSION
+    disable_repos
+  else
+    logger -st RightScale "Installing RightLink development packages with version $RS_SRC from dev repo $RIGHTLINK_DEV_REPO"
+    enable_repos $RIGHTLINK_DEV_REPO
+    install_packages $RS_SRC
+    disable_repos
+  fi
+  service rightboot start
+  service rightscale start
+  service rightlink start
   exit 0
 }
 
